version: '3'
services:
    majorproject-rest-server:
        image: 145555723369.dkr.ecr.us-east-1.amazonaws.com/backend
        build:
            context: majorproject
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        environment:
            MARIADB_HOST: ${MARIADB_HOST}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    majorproject-frontend:
        image: 145555723369.dkr.ecr.us-east-1.amazonaws.com/frontend
        build:
            context: FrontEnd
            dockerfile: Dockerfile
        ports:
            - "80:3000"
        restart: always
        stdin_open: true
        depends_on:
            - majorproject-rest-server