apiVersion: v1
kind: Service
metadata:
  name: "project-service"
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: "frontend-port"
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: "backend-port"
  type: LoadBalancer
  selector:
    app: "project"